/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AnnotationEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "annotationHashes"
      | "batches"
      | "deposit"
      | "getAnnotationHashes"
      | "getBatchAnnotators"
      | "isBatchFunded"
      | "owner"
      | "paymentToken"
      | "platformFeeBps"
      | "recordAnnotation"
      | "releasePaymentWithSplits"
      | "renounceOwnership"
      | "transferOwnership"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnnotationRecorded"
      | "FundsDeposited"
      | "FundsReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "annotationHashes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnnotationHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchAnnotators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBatchFunded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordAnnotation",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePaymentWithSplits",
    values: [BytesLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "annotationHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAnnotationHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchAnnotators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBatchFunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAnnotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePaymentWithSplits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace AnnotationRecordedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    annotator: AddressLike,
    annotationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    annotator: string,
    annotationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    annotator: string;
    annotationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    company: AddressLike,
    amount: BigNumberish,
    annotators: AddressLike[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    company: string,
    amount: bigint,
    annotators: string[],
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    company: string;
    amount: bigint;
    annotators: string[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    amountPerAnnotator: BigNumberish,
    platformFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    amountPerAnnotator: bigint,
    platformFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    amountPerAnnotator: bigint;
    platformFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnnotationEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AnnotationEscrow;
  waitForDeployment(): Promise<this>;

  interface: AnnotationEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  annotationHashes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        company: string;
        totalAmount: bigint;
        released: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<
    [batchId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAnnotationHashes: TypedContractMethod<
    [batchId: BytesLike],
    [string[]],
    "view"
  >;

  getBatchAnnotators: TypedContractMethod<
    [batchId: BytesLike],
    [string[]],
    "view"
  >;

  isBatchFunded: TypedContractMethod<[batchId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  recordAnnotation: TypedContractMethod<
    [batchId: BytesLike, annotationHash: BytesLike],
    [void],
    "nonpayable"
  >;

  releasePaymentWithSplits: TypedContractMethod<
    [batchId: BytesLike, annotators: AddressLike[], splitBps: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "annotationHashes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        company: string;
        totalAmount: bigint;
        released: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [batchId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAnnotationHashes"
  ): TypedContractMethod<[batchId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBatchAnnotators"
  ): TypedContractMethod<[batchId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isBatchFunded"
  ): TypedContractMethod<[batchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordAnnotation"
  ): TypedContractMethod<
    [batchId: BytesLike, annotationHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releasePaymentWithSplits"
  ): TypedContractMethod<
    [batchId: BytesLike, annotators: AddressLike[], splitBps: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AnnotationRecorded"
  ): TypedContractEvent<
    AnnotationRecordedEvent.InputTuple,
    AnnotationRecordedEvent.OutputTuple,
    AnnotationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AnnotationRecorded(bytes32,address,bytes32,uint256)": TypedContractEvent<
      AnnotationRecordedEvent.InputTuple,
      AnnotationRecordedEvent.OutputTuple,
      AnnotationRecordedEvent.OutputObject
    >;
    AnnotationRecorded: TypedContractEvent<
      AnnotationRecordedEvent.InputTuple,
      AnnotationRecordedEvent.OutputTuple,
      AnnotationRecordedEvent.OutputObject
    >;

    "FundsDeposited(bytes32,address,uint256,address[],uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsReleased(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
